services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["/opt/app/docker-entrypoint.sh"]
    ports:
      - 5000:5000
    # env_file: ./backend/.env
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - "./frontend:/usr/src/app"
  #     - "/usr/src/app/node_modules"
  #   ports:
  #     - 3002:3000
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5004
  #   depends_on:
  #     - backend
